version: '3.8'
services:
  database:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_DB=$DATABASE_NAME
    volumes:
      - $DATABASE_DATA_PATH:/var/lib/postgresql/data
    ports:
      - 5432:5432
